CREATE TABLE `{{table}}` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ad_id` char(32) NOT NULL,
  `income` INT(10) DEFAULT 0,
  `transfer` INT(10) UNSIGNED DEFAULT 0,
  `cpa` INT(10) UNSIGNED DEFAULT 0,
  `quote_rmb` VARCHAR(20) DEFAULT NULL,
  `real_price` SMALLINT(5) DEFAULT 0,
  `step_rmb` VARCHAR(20) DEFAULT NULL,
  `out` INT(10) UNSIGNED DEFAULT 0,
  `rmb_out` INT(10) UNSIGNED DEFAULT 0,
  `task_out` INT(10) UNSIGNED DEFAULT 0,
  `publisher_out` INT(10) UNSIGNED DEFAULT 0,
  `activity_out` INT(10) UNSIGNED DEFAULT 0,
  `activity_income` INT(10) UNSIGNED DEFAULT 0,
  `cut` INT(10) UNSIGNED DEFAULT 0,
  `happy_lock_income` INT(10) UNSIGNED DEFAULT 0,
  `happy_lock_rmb` INT(10) UNSIGNED DEFAULT 0,
  `happy_lock_transfer` INT(10) UNSIGNED DEFAULT 0,
  `publisher_transfer` INT(10) UNSIGNED DEFAULT 0,
  `publisher_cpa` INT(10) UNSIGNED DEFAULT 0,
  `publisher_income` INT(10) UNSIGNED DEFAULT 0,
  `publisher_cut` INT(10) UNSIGNED DEFAULT 0,
  `profit` INT(10) DEFAULT 0,
  `profit_ratio` SMALLINT(5) DEFAULT 0,
  `beprice` SMALLINT(5) DEFAULT 0,
  `owner` SMALLINT(5) DEFAULT NULL,
  `quoted_transfer` INT(10) UNSIGNED DEFAULT 0,
  `click` INT(10) UNSIGNED DEFAULT 0,
  `cpc` INT(10) UNSIGNED DEFAULT 0,
  `cpc_quote` VARCHAR(20) DEFAULT NULL,
  `cpc_income` INT(10) UNSIGNED DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `ad_id_index` (`ad_id`),
  KEY `owner_index` (`owner`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='广告数据分析{{start}}至{{end}}缓存'
